x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-etl_user}:${POSTGRES_PASSWORD:-etl_password}@${POSTGRES_HOST:-postgres}/${POSTGRES_DB:-ecommerce_events}
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: '${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-true}'
    AIRFLOW__CORE__LOAD_EXAMPLES: '${AIRFLOW__CORE__LOAD_EXAMPLES:-false}'
    # Spark Configs for Airflow
    SPARK_MASTER_URL: spark://spark-master:7077
    POSTGRES_USER: ${POSTGRES_USER:-etl_user}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-etl_password}
    POSTGRES_DB: ${POSTGRES_DB:-ecommerce_events}
    POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
  volumes:
    - ./dags:/opt/airflow/dags
    - ./scripts:/opt/airflow/scripts
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_events}
      POSTGRES_USER: ${POSTGRES_USER:-etl_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-etl_password}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U etl_user -d ecommerce_events"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  spark-master:
    image: apache/spark:latest
    container_name: spark_master
    user: root
    ports:
      - "8081:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./data/jars/postgresql-42.6.0.jar:/opt/spark/jars/postgresql-42.6.0.jar

  spark-worker:
    image: apache/spark:latest
    container_name: spark_worker
    user: root
    depends_on:
      - spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./scripts:/opt/spark/scripts
      - ./data:/opt/spark/data
      - ./data/jars/postgresql-42.6.0.jar:/opt/spark/jars/postgresql-42.6.0.jar

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8085:8080"
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow_scheduler
    restart: always

  airflow-init:
    <<: *airflow-common
    command: version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD:-airflow}
    container_name: airflow_init

volumes:
  postgres_data:
